[colors]
background = "#18120c"
foreground = "#eee0d4"
cursor_bg = "#eee0d4"
cursor_border = "#eee0d4"
cursor_fg = "#d4c4b5"
selection_bg = "#dfc2a2"
selection_fg = "#3f2d17"

split = "#dfc2a2"

ansi = [
    "#191919",
    "#D90202",
    "#7FB11B",
    "#FFD739",
    "#3570D7",
    "#BE84FF",
    "#66D9EF",
    "#F8F8F8",
]

brights = [
    "#4D4D4D",
    "#FF4747",
    "#A0D04D",
    "#FFEB4D",
    "#6A9FF7",
    "#D9A6FF",
    "#80F5FF",
    "#FFFFFF",
]
