[colors]
background = "#111318"
foreground = "#e2e2e9"
cursor_bg = "#e2e2e9"
cursor_border = "#e2e2e9"
cursor_fg = "#c4c6d0"
selection_bg = "#bfc6dc"
selection_fg = "#293041"

split = "#bfc6dc"

ansi = [
    "#191919",
    "#D90202",
    "#7FB11B",
    "#FFD739",
    "#3570D7",
    "#BE84FF",
    "#66D9EF",
    "#F8F8F8",
]

brights = [
    "#4D4D4D",
    "#FF4747",
    "#A0D04D",
    "#FFEB4D",
    "#6A9FF7",
    "#D9A6FF",
    "#80F5FF",
    "#FFFFFF",
]
