[colors]
background = "#1a110f"
foreground = "#f1dfda"
cursor_bg = "#f1dfda"
cursor_border = "#f1dfda"
cursor_fg = "#d8c2bc"
selection_bg = "#e7bdb2"
selection_fg = "#442a22"

split = "#e7bdb2"

ansi = [
    "#191919",
    "#D90202",
    "#7FB11B",
    "#FFD739",
    "#3570D7",
    "#BE84FF",
    "#66D9EF",
    "#F8F8F8",
]

brights = [
    "#4D4D4D",
    "#FF4747",
    "#A0D04D",
    "#FFEB4D",
    "#6A9FF7",
    "#D9A6FF",
    "#80F5FF",
    "#FFFFFF",
]
